apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-ingress.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-host-reconciler.yaml
  - networkpolicy.yaml
replacements:
  - source:
      kind: ConfigMap
      name: portfolio-ingress-config
      fieldPath: data.host
    targets:
      - select:
          kind: Ingress
          name: portfolio
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
