apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-letsencrypt.yaml
  - clusterissuer-http01.yaml
replacements:
  - source:
      kind: ConfigMap
      name: letsencrypt-config
      fieldPath: data.email
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt-http01
        fieldPaths:
          - spec.acme.email
